name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Before Install
        run: docker build -t docker-react -f Dockerfile.dev .
      - name: Test Script
        run: docker run -e CI=true docker-react npm run test
